version: '2'
services:
  # Blablabla, ngnix et PHP si vous voulez

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - cluster.name=demo
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    links:
      - elasticsearch
    ports:
      - 5601:5601